---
title: "Cookbook"
author: "Alex Kodess"
date: "May 4, 2017"
output: html_document
---
amkodess@gmail.com

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = TRUE) -->
<!-- ``` -->

## Variables

All variables except `subject` and `activity` are averages taken from merged test set 
and training set groupped by subject and activity.

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(knitr)
f_output <- read_table2(
                        file = "final_output.txt", 
                        col_types = paste0("ic", reduce(rep("d", 86), paste0))
)

to_print <- tibble(
                        var_name = names(f_output), 
                        #type = character(),
                        units = if_else(
                                        grepl("[Aa][Nn][Gg][Ll][Ee]", var_name), "rad", 
                                if_else(
                                        grepl("[Gg][Yy][Rr][Oo]", var_name), "rad/sec", 
                                if_else(
                                        grepl("[Aa][Cc][Cc]", var_name), "g", "NA"
                                )
                                )
                                ),
                        type = "numeric"
                        )

to_print[1,3] <- "integer"
to_print[2,3] <- "character"

kable(to_print)
```



```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo = 2:3}
#plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
